In [1]:
# image grayscale, binaryization
def threshold(image):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    ret, image = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
    return image

In [14]:
import cv2
import os
import numpy as np

# 이미지 불러오기
sheet = './data/school_bell.jpg'
image = cv2.imread(sheet)

# 1. 보표 영역 추출 및 그 외 노이즈 제거
image = threshold(image)  # 이미지 이진화
mask = np.zeros(image.shape, np.uint8)  # 보표 영역만 추출하기 위해 마스크 생성
print(mask)

cnt, labels, stats, centroids = cv2.connectedComponentsWithStats(image)  # 레이블링
# (cnt: 객체 수, labels: 레이블맵 행렬, stats: 객체 정보, centroids: 무게 중심 좌표)
# stats에는 x좌표, y좌표, 넓이, 높이, 픽셀의 개수 등의 정보가 담겨있다.

for i in range(1, cnt):
    x, y, w, h, area = stats[i]
    if w > image.shape[1] * 0.5:  # 보표 영역에만
        cv2.rectangle(mask, (x, y, w, h), (255, 0, 0), -1)  # 사각형 그리기
'''
마스크 이미지에 사각형을 그릴 때 rectangle 함수의 마지막 파라미터가 -1로 바뀌게 되는데,
이는 사각형에서 테두리만을 그리는 게 아니라 사각형 안을 채워 그려 넣음을 의미한다.
and 연산은 두 이미지에서 흰색 부분만을 합치는 것을 의미하기에 save 폴더의 school-bell-masked-img.png 와 같은 이미지가 나온다.
'''

masked_image = cv2.bitwise_and(image, mask)  # 보표 영역 추출

# 이미지 띄우기
# cv2.imwrite('./save/school-bell-gray.png', img)
# cv2.imwrite('./save/school-bell-masked-img.png', masked_image)
# cv2.imshow('sheet', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
